name: build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      
      # Set NODE_OPTIONS environment variable here
      - name: Set NODE_OPTIONS
        run: echo "NODE_OPTIONS=--openssl-legacy-provider" >> $GITHUB_ENV
      
      - name: install
        run: yarn

      - name: build
        run: yarn build
